"""initial schema: users, patients, vital_signs, activity_data

Revision ID: 1
Revises:
Create Date: 2026-07-14

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '381c02a6c735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'clinician', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=True),
    sa.Column('mrn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', 'other', 'unspecified', name='sex'), nullable=False),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('care_unit', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_of_birth <= CURRENT_DATE', name='ck_patient_dob_past'),
    sa.CheckConstraint('length(trim(first_name)) > 0', name='ck_patient_first_name_not_blank'),
    sa.CheckConstraint('length(trim(last_name)) > 0', name='ck_patient_last_name_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_patients_care_unit', 'patients', ['care_unit'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('activity_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', app.models.GUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('steps', 'calories_burned', 'active_minutes', 'sleep_hours', 'distance_km', name='activitytype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_activity_value_non_negative'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'activity_type', 'recorded_date', name='uq_activity_patient_type_date')
    )
    op.create_index('ix_activity_patient_date', 'activity_data', ['patient_id', 'recorded_date'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', app.models.GUID(), nullable=False),
    sa.Column('vital_type', sa.Enum('heart_rate', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'spo2', 'blood_glucose', 'temperature', name='vitaltype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=15), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.CheckConstraint("((vital_type = 'heart_rate' AND value BETWEEN 20 AND 300) OR (vital_type = 'blood_pressure_systolic' AND value BETWEEN 40 AND 300) OR (vital_type = 'blood_pressure_diastolic' AND value BETWEEN 20 AND 200) OR (vital_type = 'spo2' AND value BETWEEN 0 AND 100) OR (vital_type = 'blood_glucose' AND value BETWEEN 10 AND 900) OR (vital_type = 'temperature' AND value BETWEEN 25 AND 45))", name='ck_vital_value_in_range'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vitals_patient_recorded', 'vital_signs', ['patient_id', 'recorded_at'], unique=False)
    op.create_index('ix_vitals_patient_type_recorded', 'vital_signs', ['patient_id', 'vital_type', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vitals_patient_type_recorded', table_name='vital_signs')
    op.drop_index('ix_vitals_patient_recorded', table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index('ix_activity_patient_date', table_name='activity_data')
    op.drop_table('activity_data')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index('ix_patients_care_unit', table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
