"""
HealthTrack Phase 3 API.

Run locally with:
    uvicorn app.main:app --reload

Interactive docs are auto-generated by FastAPI at /docs (Swagger UI) and
/redoc, from the OpenAPI schema this module builds from the Pydantic
schemas and route declarations below.
"""
from datetime import datetime, date
from typing import Optional
from uuid import UUID

from fastapi import FastAPI, Depends, HTTPException, status, Query
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session

from app import crud, models, schemas
from app import alert_crud, alert_models, alert_schemas  # noqa: F401 (alert_models import registers its tables on Base.metadata)
from app.alert_models import AlertStatus, Notification, Severity, VitalThreshold
from app.database import get_db, engine, Base
from app.auth import (
    hash_password, verify_password, create_access_token,
    get_current_user, require_role,
)
from app.logging_config import access_logger, error_logger

# NOTE: In production, schema creation/updates are handled by Alembic
# migrations (see migrations/), not by create_all(). create_all() is kept
# here only as a safety net for first-run local development. Importing
# app.alert_models above (Phase 4) before this call matters: SQLAlchemy
# only creates tables for models it has actually seen, so if alert_models
# were imported later, Base.metadata.create_all() here would silently
# skip the alerts/thresholds/notifications tables.
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="HealthTrack API — Phase 3",
    description=(
        "Backend implementation for patient records, vital sign capture, "
        "and activity tracking, built on FastAPI + SQLAlchemy. "
        "See the accompanying technical documentation for a plain-English "
        "walkthrough with references."
    ),
    version="3.0.0",
)


# ---------------------------------------------------------------------
# Centralized exception handling
# ---------------------------------------------------------------------

@app.exception_handler(crud.NotFoundError)
async def not_found_handler(request, exc: crud.NotFoundError):
    return JSONResponse(status_code=404, content={"error_code": "NOT_FOUND", "message": str(exc)})


@app.exception_handler(crud.DuplicateError)
async def duplicate_handler(request, exc: crud.DuplicateError):
    return JSONResponse(status_code=409, content={"error_code": "DUPLICATE", "message": str(exc)})


@app.exception_handler(crud.ValidationFailedError)
async def validation_failed_handler(request, exc: crud.ValidationFailedError):
    return JSONResponse(status_code=422, content={"error_code": "VALIDATION_FAILED", "message": str(exc)})


@app.exception_handler(alert_crud.NotFoundError)
async def alert_not_found_handler(request, exc: alert_crud.NotFoundError):
    return JSONResponse(status_code=404, content={"error_code": "NOT_FOUND", "message": str(exc)})


@app.exception_handler(alert_crud.InvalidStateTransitionError)
async def invalid_state_transition_handler(request, exc: alert_crud.InvalidStateTransitionError):
    return JSONResponse(status_code=409, content={"error_code": "INVALID_STATE_TRANSITION", "message": str(exc)})


@app.exception_handler(Exception)
async def unhandled_exception_handler(request, exc: Exception):
    error_logger.exception(f"Unhandled exception on {request.method} {request.url.path}: {exc}")
    return JSONResponse(
        status_code=500,
        content={"error_code": "INTERNAL_ERROR", "message": "An unexpected error occurred."},
    )


# ---------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------

@app.get("/health", tags=["Health"])
def health_check():
    return {"status": "ok"}


@app.get("/dashboard/patients", tags=["Dashboard"])
def dashboard_patients(db: Session = Depends(get_db)):
    items, total = crud.list_patients(db, page=1, page_size=200)
    return [
        {
            "id": p.id,
            "mrn": p.mrn,
            "name": f"{p.first_name} {p.last_name}",
            "care_unit": p.care_unit,
        }
        for p in items
    ]


@app.get("/dashboard/patient/{patient_id}/live", tags=["Dashboard"])
def dashboard_patient_live(patient_id: UUID, db: Session = Depends(get_db)):
    patient = crud.get_patient(db, patient_id)
    vitals, _ = crud.list_vital_signs(db, patient_id=patient_id, page=1, page_size=20)
    activities, _ = crud.list_activity_data(db, patient_id=patient_id, page=1, page_size=20)
    alerts, _ = alert_crud.list_alerts(db, patient_id=patient_id, status=AlertStatus.open, page=1, page_size=10)
    return {
        "patient": {
            "id": patient.id,
            "mrn": patient.mrn,
            "name": f"{patient.first_name} {patient.last_name}",
            "care_unit": patient.care_unit,
        },
        "vitals": [
            {
                "id": v.id,
                "vital_type": v.vital_type.value,
                "value": float(v.value),
                "unit": v.unit,
                "recorded_at": v.recorded_at.isoformat(),
                "is_flagged": v.is_flagged,
            }
            for v in vitals
        ],
        "activities": [
            {
                "id": a.id,
                "activity_type": a.activity_type.value,
                "value": float(a.value),
                "unit": a.unit,
                "recorded_date": a.recorded_date.isoformat(),
            }
            for a in activities
        ],
        "alerts": [
            {
                "id": str(alert.id),
                "rule_type": alert.rule_type,
                "severity": alert.severity.value,
                "status": alert.status.value,
                "message": alert.message,
                "created_at": alert.created_at.isoformat(),
            }
            for alert in alerts
        ],
    }


@app.get("/", tags=["Root"])
def root():
    return {"status": "ok", "message": "HealthTrack API — see /docs for endpoints"}


# ---------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------

@app.post("/auth/register", response_model=schemas.UserOut, status_code=201, tags=["Auth"])
def register(payload: schemas.UserCreate, db: Session = Depends(get_db)):
    """Create a new user account. In production, self-registration would
    typically be restricted to the 'patient' role, with clinician/admin
    accounts provisioned by an administrator; left open here for testing."""
    existing = crud.get_user_by_email(db, payload.email)
    if existing:
        raise crud.DuplicateError(f"A user with email '{payload.email}' already exists.")
    user = crud.create_user(
        db, email=payload.email, hashed_password=hash_password(payload.password), role=payload.role
    )
    return user


@app.post("/auth/login", response_model=schemas.Token, tags=["Auth"])
def login(payload: schemas.LoginRequest, db: Session = Depends(get_db)):
    user = crud.get_user_by_email(db, payload.email)
    if not user or not verify_password(payload.password, user.hashed_password):
        access_logger.warning(f"Failed login attempt for {payload.email}")
        raise HTTPException(status_code=401, detail="Incorrect email or password.")
    if not user.is_active:
        raise HTTPException(status_code=403, detail="This account has been deactivated.")
    token, expires_in = create_access_token(str(user.id), user.role.value)
    access_logger.info(f"Successful login: {user.email}")
    return schemas.Token(access_token=token, expires_in=expires_in)


@app.get("/auth/me", response_model=schemas.UserOut, tags=["Auth"])
def read_current_user(current_user: models.User = Depends(get_current_user)):
    return current_user


# ---------------------------------------------------------------------
# Patients
# ---------------------------------------------------------------------

def _assert_patient_access(current_user: models.User, patient: models.Patient):
    """Row-level ownership check: a patient may only access their own
    record; clinicians/admins may access any patient."""
    if current_user.role == models.UserRole.patient and str(patient.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="You do not have access to this patient's records.")


@app.post(
    "/patients", response_model=schemas.PatientOut, status_code=201, tags=["Patients"],
    dependencies=[Depends(require_role(models.UserRole.clinician, models.UserRole.admin))],
)
def create_patient(payload: schemas.PatientCreate, db: Session = Depends(get_db)):
    """Create a new patient record. Restricted to clinicians/admins (intake workflow)."""
    return crud.create_patient(db, **payload.model_dump())


@app.get("/patients", tags=["Patients"])
def list_patients(
    care_unit: Optional[str] = None,
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(require_role(models.UserRole.clinician, models.UserRole.admin)),
):
    """List patients, optionally filtered by care unit. Clinicians/admins only."""
    items, total = crud.list_patients(db, care_unit=care_unit, page=page, page_size=page_size)
    return {
        "total": total, "page": page, "page_size": page_size,
        "items": [schemas.PatientOut.model_validate(p) for p in items],
    }


@app.get("/patients/{patient_id}", response_model=schemas.PatientOut, tags=["Patients"])
def get_patient(
    patient_id: UUID, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)
    return patient


@app.put(
    "/patients/{patient_id}", response_model=schemas.PatientOut, tags=["Patients"],
    dependencies=[Depends(require_role(models.UserRole.clinician, models.UserRole.admin))],
)
def update_patient(patient_id: UUID, payload: schemas.PatientUpdate, db: Session = Depends(get_db)):
    return crud.update_patient(db, patient_id, **payload.model_dump(exclude_unset=True))


@app.delete(
    "/patients/{patient_id}", status_code=204, tags=["Patients"],
    dependencies=[Depends(require_role(models.UserRole.admin))],
)
def delete_patient(patient_id: UUID, db: Session = Depends(get_db)):
    crud.delete_patient(db, patient_id)


# ---------------------------------------------------------------------
# Vital Signs
# ---------------------------------------------------------------------

@app.post("/patients/{patient_id}/vitals", response_model=schemas.VitalSignsOut, status_code=201, tags=["Vitals"])
def create_vital_signs(
    patient_id: UUID, payload: schemas.VitalSignsBase, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Record a new vital sign reading for a patient, then evaluate it
    against the applicable threshold rules and create/update an Alert
    if it breaches one (see app/alert_crud.process_new_vital_sign)."""
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)
    data = payload.model_dump()
    data["patient_id"] = str(patient_id)
    vital = crud.create_vital_signs(db, **data)
    alert_crud.process_new_vital_sign(db, vital)
    return vital


@app.get("/patients/{patient_id}/vitals", tags=["Vitals"])
def list_vital_signs(
    patient_id: UUID,
    vital_type: Optional[models.VitalType] = None,
    start_date: Optional[datetime] = Query(None, description="Inclusive lower bound on recorded_at"),
    end_date: Optional[datetime] = Query(None, description="Inclusive upper bound on recorded_at"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=500),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """List a patient's vital sign readings, most recent first, with optional
    filtering by vital type and/or date range."""
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)
    items, total = crud.list_vital_signs(
        db, patient_id=patient_id, vital_type=vital_type,
        start_date=start_date, end_date=end_date, page=page, page_size=page_size,
    )
    return {
        "total": total, "page": page, "page_size": page_size,
        "items": [schemas.VitalSignsOut.model_validate(v) for v in items],
    }


@app.delete("/vitals/{vital_id}", status_code=204, tags=["Vitals"])
def delete_vital_signs(
    vital_id: int, db: Session = Depends(get_db),
    current_user: models.User = Depends(require_role(models.UserRole.clinician, models.UserRole.admin)),
):
    crud.delete_vital_signs(db, vital_id)


# ---------------------------------------------------------------------
# Activity Data
# ---------------------------------------------------------------------

@app.post("/patients/{patient_id}/activity", response_model=schemas.ActivityDataOut, status_code=201, tags=["Activity"])
def create_activity_data(
    patient_id: UUID, payload: schemas.ActivityDataBase, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Record a daily activity summary (steps, active minutes, etc.) for a
    patient, then evaluate it against active pattern rules and
    create/update Alert(s) for any breach detected."""
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)
    data = payload.model_dump()
    data["patient_id"] = str(patient_id)
    activity = crud.create_activity_data(db, **data)
    alert_crud.process_new_activity_data(db, activity)
    return activity


@app.get("/patients/{patient_id}/activity", tags=["Activity"])
def list_activity_data(
    patient_id: UUID,
    activity_type: Optional[models.ActivityType] = None,
    start_date: Optional[date] = Query(None, description="Inclusive lower bound on recorded_date"),
    end_date: Optional[date] = Query(None, description="Inclusive upper bound on recorded_date"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=500),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """List a patient's activity entries, most recent first, with optional
    filtering by activity type and/or date range."""
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)
    items, total = crud.list_activity_data(
        db, patient_id=patient_id, activity_type=activity_type,
        start_date=start_date, end_date=end_date, page=page, page_size=page_size,
    )
    return {
        "total": total, "page": page, "page_size": page_size,
        "items": [schemas.ActivityDataOut.model_validate(a) for a in items],
    }


@app.delete("/activity/{activity_id}", status_code=204, tags=["Activity"])
def delete_activity_data(
    activity_id: int, db: Session = Depends(get_db),
    current_user: models.User = Depends(require_role(models.UserRole.clinician, models.UserRole.admin)),
):
    crud.delete_activity_data(db, activity_id)


# ---------------------------------------------------------------------
# Thresholds (patient-specific vital-sign overrides)
# ---------------------------------------------------------------------

@app.post(
    "/patients/{patient_id}/thresholds", response_model=alert_schemas.ThresholdResponse,
    status_code=201, tags=["Alerts"],
)
def create_threshold(
    patient_id: UUID, payload: alert_schemas.ThresholdCreateRequest, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Create a patient-specific threshold override. Patient-specific
    thresholds take priority over the global defaults for that patient +
    vital_type combination (see app/alert_rules.evaluate_vital_threshold)."""
    patient = crud.get_patient(db, patient_id)
    _assert_patient_access(current_user, patient)

    threshold = VitalThreshold(
        patient_id=str(patient_id), vital_type=payload.vital_type, severity=payload.severity,
        min_value=payload.min_value, max_value=payload.max_value, is_active=True,
    )
    db.add(threshold)
    db.commit()
    db.refresh(threshold)
    return threshold


# ---------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------

@app.get("/alerts", response_model=alert_schemas.AlertListResponse, tags=["Alerts"])
def list_alerts(
    patient_id: Optional[UUID] = None,
    status_filter: Optional[AlertStatus] = Query(default=None, alias="status"),
    severity: Optional[Severity] = None,
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    items, total = alert_crud.list_alerts(
        db, patient_id=patient_id, status=status_filter, severity=severity, page=page, page_size=page_size,
    )
    return alert_schemas.AlertListResponse(items=items, total=total)


@app.get("/alerts/{alert_id}", response_model=alert_schemas.AlertDetailResponse, tags=["Alerts"])
def get_alert(alert_id: UUID, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    return alert_crud.get_alert(db, alert_id)


@app.post("/alerts/{alert_id}/acknowledge", response_model=alert_schemas.AlertResponse, tags=["Alerts"])
def acknowledge_alert(
    alert_id: UUID, payload: alert_schemas.AlertActionRequest, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    return alert_crud.acknowledge_alert(db, alert_id, current_user, notes=payload.notes)


@app.post("/alerts/{alert_id}/resolve", response_model=alert_schemas.AlertResponse, tags=["Alerts"])
def resolve_alert(
    alert_id: UUID, payload: alert_schemas.AlertActionRequest, db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    return alert_crud.resolve_alert(db, alert_id, current_user, notes=payload.notes or "")


@app.post(
    "/alerts/run-escalation-check", response_model=alert_schemas.EscalationCheckResponse, tags=["Alerts"],
)
def run_escalation_check(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(require_role(models.UserRole.admin)),
):
    """Sweep every open alert past its escalation window and escalate it.
    Restricted to admins since this is a system-wide operator action, not
    something scoped to one patient or clinician."""
    escalated = alert_crud.run_escalation_check(db)
    return alert_schemas.EscalationCheckResponse(escalated_count=len(escalated))


# ---------------------------------------------------------------------
# Notifications (for the current user)
# ---------------------------------------------------------------------

@app.get("/notifications", response_model=list[alert_schemas.NotificationResponse], tags=["Alerts"])
def list_my_notifications(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    from sqlalchemy import select as _select

    stmt = (
        _select(Notification)
        .where(Notification.user_id == current_user.id)
        .order_by(Notification.created_at.desc())
    )
    return db.execute(stmt).scalars().all()
