"""initial schema

Revision ID: 9f445de9e738
Revises: 
Create Date: 2026-08-16 02:29:59.775941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f445de9e738'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('primary_condition', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('NURSE', 'PHYSICIAN', 'ADMIN', 'TAM', name='staffrole'), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_serial', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial')
    )
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('diastolic_bp', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('consciousness_level', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vitals_patient_time', 'vital_signs', ['patient_id', 'recorded_at'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vital_sign_id', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('news2_score', sa.Integer(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['vital_sign_id'], ['vital_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_patient_time', 'risk_assessments', ['patient_id', 'assessed_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'ESCALATED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_assessment_patient_time', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_vitals_patient_time', table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_table('devices')
    op.drop_table('staff')
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
